[PHP]
extension_dir = "C:\Users\nethm\AppData\Local\Microsoft\WinGet\Packages\PHP.PHP.8.2_Microsoft.Winget.Source_8wekyb3d8bbwe\ext"
extension=pdo_mysql
extension=mysqli
extension=curl
extension=fileinfo
extension=mbstring
extension=openssl
extension=gd
session.save_path = "C:\Windows\Temp"
upload_max_filesize = 20M
post_max_size = 25M
display_errors = On
display_startup_errors = On
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
